### ISSUE TITLE
Issues with Puppet 4.5.3 and Rspec-Puppet

### ISSUE THREAD

**Issue by tobru** [vshn/puppet-gitlab#85]
Some strange issues with Puppet 4.5.3 and Rspec-Puppet:

```
Failures:

  1) gitlab supported operating systems gitlab class without any parameters on Debian (Jessie) should contain Class[gitlab::install] that comes before gitlab::config

     Failure/Error: it { is_expected.to contain_class('gitlab::install').that_comes_before('gitlab::config') }

     

     ArgumentError:

       No title provided and "gitlab::config" is not a valid resource reference

     # /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-4.5.3/lib/puppet/resource.rb:544:in `extract_type_and_title'

     # /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-4.5.3/lib/puppet/resource.rb:529:in `type_and_title'

     # /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-4.5.3/lib/puppet/resource/catalog.rb:353:in `resource'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:204:in `block in check_befores'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:203:in `each'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:203:in `check_befores'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:99:in `matches?'

     # ./spec/classes/init_spec.rb:17:in `block (4 levels) in <top (required)>'

  2) gitlab supported operating systems gitlab class without any parameters on Debian (Jessie) should contain Class[gitlab::service] that subscribes to gitlab::config

     Failure/Error: it { is_expected.to contain_class('gitlab::service').that_subscribes_to('gitlab::config') }

     

     ArgumentError:

       No title provided and "gitlab::config" is not a valid resource reference

     # /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-4.5.3/lib/puppet/resource.rb:544:in `extract_type_and_title'

     # /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-4.5.3/lib/puppet/resource.rb:529:in `type_and_title'

     # /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-4.5.3/lib/puppet/resource/catalog.rb:353:in `resource'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:228:in `block in check_subscribes'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:227:in `each'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:227:in `check_subscribes'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:102:in `matches?'

     # ./spec/classes/init_spec.rb:19:in `block (4 levels) in <top (required)>'

  3) gitlab supported operating systems gitlab class without any parameters on RedHat (CentOS) should contain Class[gitlab::install] that comes before gitlab::config

     Failure/Error: it { is_expected.to contain_class('gitlab::install').that_comes_before('gitlab::config') }

     

     ArgumentError:

       No title provided and "gitlab::config" is not a valid resource reference

     # /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-4.5.3/lib/puppet/resource.rb:544:in `extract_type_and_title'

     # /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-4.5.3/lib/puppet/resource.rb:529:in `type_and_title'

     # /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-4.5.3/lib/puppet/resource/catalog.rb:353:in `resource'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:204:in `block in check_befores'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:203:in `each'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:203:in `check_befores'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:99:in `matches?'

     # ./spec/classes/init_spec.rb:53:in `block (4 levels) in <top (required)>'

  4) gitlab supported operating systems gitlab class without any parameters on RedHat (CentOS) should contain Class[gitlab::service] that subscribes to gitlab::config

     Failure/Error: it { is_expected.to contain_class('gitlab::service').that_subscribes_to('gitlab::config') }

     

     ArgumentError:

       No title provided and "gitlab::config" is not a valid resource reference

     # /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-4.5.3/lib/puppet/resource.rb:544:in `extract_type_and_title'

     # /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-4.5.3/lib/puppet/resource.rb:529:in `type_and_title'

     # /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-4.5.3/lib/puppet/resource/catalog.rb:353:in `resource'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:228:in `block in check_subscribes'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:227:in `each'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:227:in `check_subscribes'

     # /home/travis/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-puppet-79d5373dcbfa/lib/rspec-puppet/matchers/create_generic.rb:102:in `matches?'

     # ./spec/classes/init_spec.rb:55:in `block (4 levels) in <top (required)>'

Finished in 16.74 seconds (files took 1 second to load)

44 examples, 4 failures

Failed examples:

rspec ./spec/classes/init_spec.rb:17 # gitlab supported operating systems gitlab class without any parameters on Debian (Jessie) should contain Class[gitlab::install] that comes before gitlab::config

rspec ./spec/classes/init_spec.rb:19 # gitlab supported operating systems gitlab class without any parameters on Debian (Jessie) should contain Class[gitlab::service] that subscribes to gitlab::config

rspec ./spec/classes/init_spec.rb:53 # gitlab supported operating systems gitlab class without any parameters on RedHat (CentOS) should contain Class[gitlab::install] that comes before gitlab::config

rspec ./spec/classes/init_spec.rb:55 # gitlab supported operating systems gitlab class without any parameters on RedHat (CentOS) should contain Class[gitlab::service] that subscribes to gitlab::config
```

**Comment by tobru** [comment]
See also https://tickets.puppetlabs.com/browse/PUP-6385

**Comment by tobru** [comment]
Test locally:

```
docker run --rm -it -v $(pwd):/home/travis/gitlab quay.io/travisci/travis-ruby /bin/bash
su - travis
cd gitlab
export PUPPET_VERSION="~> 4.5.3"
export STRICT_VARIABLES=yes
rvm use 2.3.0 --install --binary --fuzzy
export BUNDLE_GEMFILE=$PWD/Gemfile
rm Gemfile.lock || true
bundle install --without development system_tests
bundle exec rake test
```
